version: 2.1

jobs:
  build:
    docker:
      - image: helloworld
    steps:
      - checkout
      - run: Dockerfile
  test:
    docker:
      - image: helloworld
    steps:
      - checkout
      - run: helloworld
  deploy:
    docker:
      - image: helloworld
    steps:
      - run: echo "Deploying to production"

workflows:
  build_and_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build 
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main