version: 2.1

jobs:
  build:
    docker:
      - image: helloworld
        auth:
          username: mydockerhub-user  # can specify string literal values
          password: $DOCKERHUB_PASSWORD  # or project environment variable reference

workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - build-env-vars
            - docker-hub-creds
          filters:
            branches:
              only: main

