version: 2.1

workflows:
  build_and_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build 
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main

jobs:
  build:
    docker:
      - image: helloworld
    steps:
      - run: Dockerfile
      auth:
          username: mydockerhub-user  # can specify string literal values
          password: ENV NODE_ENV=production # or project environment variable reference    

  test:
    docker:
      - image: helloworld
    steps:
      - checkout
      - run: Dockerfile
  deploy:
    docker:
      - image: helloworld
    steps:
      - run: echo "Deploying to production server"




