version: 2.1

workflows:
  build_and_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build 
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main

jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t your-dockerhub-username/helloworld:latest .
            docker login -u your-dockerhub-username -p $DOCKERHUB_PASSWORD
            docker push your-dockerhub-username/helloworld:latest
    steps:
      - checkout
      - run:
          name: Extract Zip File
          command: |
            mkdir extracted
            unzip your-zip-file.zip -d extracted
 

  test:
    docker:
      - image: helloworld
    steps:
      - checkout
      - run: Dockerfile
  deploy:
    docker:
      - image: helloworld
    steps:
      - run: echo "Hello, World!"




