version: 2.1
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main

jobs:
   build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build and Push Docker Image
          command: |
           mkdir extracted
            unzip hello-world.zip -d extracted

            docker build -t your-dockerhub-username/helloworld:latest .
            docker login -u your-dockerhub-username -p $DOCKERHUB_PASSWORD
            docker push your-dockerhub-username/helloworld:latest
   
 



