version: 2.1

workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - build-env-vars
            - docker-hub-creds

jobs:
  build:
    docker:
      - image: acme-private/private-image:321
        auth:
          username: mydockerhub-user  # can specify string literal values
          password: ENV NODE_ENV=production # or project environment variable reference
          working_directory: usr/src/app
    steps:
      - checkout
      - run: Dockerfile





